### ISSUE TITLE
AttributeError: module 'obsstudio_sdk' has no attribute 'ReqClient'

### ISSUE THREAD

**Issue by DidierMalenfant** [aatikturk/obsstudio_sdk#5]
Trying to use this module to replace `obs-websocket-py` and I'm using Python 3.11.0b5.

I'm trying the sample code provided in the Readme:
```
import obsstudio_sdk as obs
self.obs = obs.ReqClient(self.server_address, self.server_port, self.server_password)
```
and I'm getting this error:
```
AttributeError: module 'obsstudio_sdk' has no attribute 'ReqClient'
```
Any idea where I'm going wrong?

**Comment by DidierMalenfant** [comment]
Yep that did the trick. I'm now getting a connection refused but that does mean that at least the method is found fine.

**Comment by aatikturk** [comment]
It's probably about the connection parameters (ip address, host, port, password). It might help to double-check them.

**Comment by DidierMalenfant** [comment]
Totally. User error on that one... Thanks for the quick help!

**Comment by aatikturk** [comment]
@onyx-and-iris checked this again and it already seemed fine with the latest version before the update (1.0.2) 

thanks to efforts of @onyx-and-iris we added support for python version 3.10 

### Any new users checking this issue, please make sure you're using the latest version **(1.0.3)**  which adds support for python 3.10
